# Introduction to Scikit-Learn (sklearn)
This notebook demostrates some of the most useful functions of the Scikit-Learn library.


0. An end-to-end Scikit-Learno Workflow
1. Gettin the data ready
2. Choose the rigth estimator/algotithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluatin a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

## 0. An end-to-end Scikit-Learn workflow

In [20]:
# Standar imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("Data/heart-disease.csv") 
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [22]:
# Create X (features matrix)
X = heart_disease.drop("target", axis=1) #axis=1 columnas

# Create y (labels)
y = heart_disease["target"]

In [23]:
# 2. Choose the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [24]:
# 3. Fit the model to the training data
# Split the data into training and test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2) #80% entretamiento y 20% para test

In [25]:
# .fit el modelo está entrenando
clf.fit(X_train, y_train);

In [26]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
22    42    1   0       140   226    0        1      178      0      0.0   
204   62    0   0       160   164    0        0      145      0      6.2   
126   47    1   0       112   204    0        1      143      0      0.1   
250   51    1   0       140   298    0        1      122      1      4.2   
274   47    1   0       110   275    0        0      118      1      1.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
177   64    1   2       140   335    0        1      158      0      0.0   
80    41    1   2       112   250    0        1      179      0      0.0   
70    54    1   2       120   258    0        0      147      0      0.4   
48    53    0   2       128   216    0        0      115      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   

     slope  ca  thal  
22       2   0     2  
204      0   3     3  
126      2   0     2  
250      1   3     3  
274      1   1     2  
..     ...  ..   ...  
177      2   0     2  
80       2   0     2  
70       1   0     3  
48       2   0     0  
32       2   0     2  

[242 rows x 13 columns]

In [27]:
# make a prediction
y_label = clf.predict(np.array([0,2,3,4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [28]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
278   58    0   1       136   319    1        0      152      0      0.0   
64    58    1   2       140   211    1        0      165      0      0.0   
257   50    1   0       144   200    0        0      126      1      0.9   
11    48    0   2       130   275    0        1      139      0      0.2   
71    51    1   2        94   227    0        1      154      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
237   60    1   0       140   293    0        0      170      0      1.2   
243   57    1   0       152   274    0        1       88      1      1.2   
262   53    1   0       123   282    0        1       95      1      2.0   
161   55    0   1       132   342    0        1      166      0      1.2   
205   52    1   0       128   255    0        1      161      1      0.0   

     slope  ca  thal  
278      2   2     2  
64       2   0     2  
257      1   0     3  
11       2   0     2  
71       2   1     3  
..     ...  ..   ...  
237      1   2     3  
243      1   1     3  
262      1   2     3  
161      2   0     2  
205      2   1     3  

[61 rows x 13 columns]

In [29]:
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0])

In [30]:
y_test

278    0
64     1
257    0
11     1
71     1
      ..
237    0
243    0
262    0
161    1
205    0
Name: target, Length: 61, dtype: int64

In [31]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train)

1.0

In [32]:
clf.score(X_test, y_test)

0.8688524590163934

In [33]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.89      0.83      0.86        29
           1       0.85      0.91      0.88        32

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61



In [34]:
confusion_matrix(y_test, y_preds)

array([[24,  5],
       [ 3, 29]])

In [35]:
accuracy_score(y_test, y_preds) #Accuracy= precisión, exactitud

0.8688524590163934

In [36]:
# 5. Improve a model
# Try different amonut of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...") # Se pone f para concatenar string con variable, en este {i}
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on teste set_{clf.score(X_test, y_test)*100:.2f}%") # :.2 es para dejar en 2 decimales
    print("")

Trying model with 10 estimators...
Model accuracy on teste set_78.69%

Trying model with 20 estimators...
Model accuracy on teste set_88.52%

Trying model with 30 estimators...
Model accuracy on teste set_83.61%

Trying model with 40 estimators...
Model accuracy on teste set_88.52%

Trying model with 50 estimators...
Model accuracy on teste set_83.61%

Trying model with 60 estimators...
Model accuracy on teste set_86.89%

Trying model with 70 estimators...
Model accuracy on teste set_85.25%

Trying model with 80 estimators...
Model accuracy on teste set_86.89%

Trying model with 90 estimators...
Model accuracy on teste set_88.52%



In [37]:
# 6. Save a model and load it
import pickle
pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

In [38]:
loaden_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaden_model.score(X_test, y_test)

0.8852459016393442

In [39]:
loaden_model.predict([[ 40.,   1.,   0., 110., 167.,   0.,   0., 114.,   1.,   2.,   1.,
         0.,   3.]])

array([0])

In [40]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
278   58    0   1       136   319    1        0      152      0      0.0   
64    58    1   2       140   211    1        0      165      0      0.0   
257   50    1   0       144   200    0        0      126      1      0.9   
11    48    0   2       130   275    0        1      139      0      0.2   
71    51    1   2        94   227    0        1      154      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
237   60    1   0       140   293    0        0      170      0      1.2   
243   57    1   0       152   274    0        1       88      1      1.2   
262   53    1   0       123   282    0        1       95      1      2.0   
161   55    0   1       132   342    0        1      166      0      1.2   
205   52    1   0       128   255    0        1      161      1      0.0   

     slope  ca  thal  
278      2   2     2  
64       2   0     2  
257      1   0     3  
11       2   0     2  
71       2   1     3  
..     ...  ..   ...  
237      1   2     3  
243      1   1     3  
262      1   2     3  
161      2   0     2  
205      2   1     3  

[61 rows x 13 columns]

In [41]:
# Para probar el modelo se toma como referencia los datos de la posición [0] con .iloc.
X_test.iloc[0].values

array([ 58.,   0.,   1., 136., 319.,   1.,   0., 152.,   0.,   0.,   2.,
         2.,   2.])

In [42]:
# Se modifican datos y se ve el resultado que arroja el modelo, siendo 1 que tiene probabilidad de tener un problema cardiaco y 0 que no.
loaden_model.predict([[ 45.,   1.,   3., 140., 187.,   0.,   1., 154.,   1.,   1.,   2.,
         4.,   2.]])

array([1])

## 1. Getting our data ready to be used with Machine Learning
Thre main thing we have to do:

    1. Split the data into features and labels (usually 'X' & 'y')
    2. Filling(also callen imputing) or disregarding missing values
    3. Converting non-numerical values to numerical values(also called feature encoding)

### 1.1 Make sure it's all numerical

In [43]:
# pd.read_csv("") = cargar csv
car_sales = pd.read_csv("Data/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [44]:
# len=largo
len(car_sales) 

1000

In [45]:
# dtype = tipo de dato
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [46]:
# Split into X/y
X = car_sales.drop("Price", axis=1) # Todas las columnas menos la columna precio
y = car_sales["Price"] # nuestra variable y será el precio, lo que queremos estimar

#Split into training and test

X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                   test_size=0.2) # 80 % entramiento, 20% test

In [47]:
# Buil ML model

from sklearn.ensemble import RandomForestRegressor # RandomrForestRegressor predice números

model = RandomForestRegressor()
model.fit(X_train, y_train) # se entrena el modelo con esas variables
model.score(X_test, y_test) # se obtiene precisión del modelo


ValueError: could not convert string to float: 'Honda'

In [48]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [49]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [50]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [51]:
dummies = pd.get_dummies(car_sales[["Make","Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [52]:
# Let's refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [53]:
model.score(X_test, y_test)

0.3235867221569877

In [54]:
# probando con dummies
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(dummies,
                                                   y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [55]:
model.score(X_test, y_test)

0.2920788538619685

### 1.2 What if there wre missing values?
1. Fill them with some value(also known as imputation).
2. Remove the samples with missing data altogether

In [56]:
# Import car sales missing data extended
car_sales_missing = pd.read_csv("Data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [57]:
# ver si hay datos nulos en el csv
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [58]:
# Create X & y
X = car_sales_missing.drop("Price", axis=1)
y= car_sales_missing["Price"]

In [59]:
# Let's try and convert our data in numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [60]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

## Option 1: Fill missing data with Pandas

In [61]:
# Fill the "Make" column
car_sales_missing["Make"].fillna("missing", inplace=True)

# Fill the " Colour" column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the "Odometer(KM)" column
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "doors" column
car_sales_missing["Doors"].fillna(4, inplace=True)


In [62]:
# Check our dataframe again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [63]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace=True)

In [64]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [65]:
len(car_sales_missing)

950

In [66]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [67]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### Option 2: Fill missing values with Scikit-learn

In [68]:
# Utilizamos un archivo que tenga celdas en blanco y lo abrimos.
car_sales_missing_values = pd.read_csv("Data/car-sales-extended-missing-data.csv")
car_sales_missing_values.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [69]:
# Se verifica si el archivo tiene valores en blanco.
car_sales_missing_values.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [70]:
# Se utiliza .dropna para eliminar los celdas(filas) en la columna "Price" y se vuelve a chequear la cantidad de valores en blanco.
car_sales_missing_values.dropna(subset=["Price"], inplace=True)
car_sales_missing_values.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [71]:
# Se utiliza Split para eje X & y, en eje X se elimina columna "Precios" y se conservan las demás, en el eje y se guarda sólo "Precios"
X = car_sales_missing_values.drop("Price", axis=1)
y = car_sales_missing_values["Price"]

In [72]:
# Se importa la siguiente función para rellenar valores vacios con sklearn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' & numerical values with mean
categorical_imputer = SimpleImputer(strategy = "constant", fill_value="missing")
door_imputer = SimpleImputer(strategy = "constant", fill_value=4)
numerical_imputer = SimpleImputer(strategy = "mean")

#Define columns
categorical_features = ["Make", "Colour"]
door_features = ["Doors"]
numerical_features = ["Odometer (KM)"]

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer([
    ("categorical_imputer", categorical_imputer, categorical_features),
    ("door_imputer", door_imputer, door_features),
    ("numerical_imputer", numerical_imputer, numerical_features)
])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [73]:
car_sales_filled = pd.DataFrame(filled_X,
                               columns = ["Make", "Colour", "Doors"," Odometer(KM)"])
car_sales_filled.head()

Make Colour Doors  Odometer(KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [74]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
 Odometer(KM)    0
dtype: int64

In [75]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [76]:
# Now we've got our data as numbers and filled(no missing values)
# Let's fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)
model.score(X_test,y_test)


0.21990196728583944

In [77]:
len(car_sales_filled)

950

## 2. Choosing the right estimator/algorithm for our problem
Scikit-Learn uses estimator as another term for machine learning model or algorithm

* Classification - predicting whether a sample is one thing or another
* Regression- predicting a number

Step 1 - Check the Scikit- Learn machine learning map
https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html


### 2.1 Picking a ML model for a regression problem

In [78]:
# Import Boston housing dataset (es un diccionario)
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [79]:
boston_df = pd.DataFrame(boston["data"], columns = boston ["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [80]:
# How many samples have Boston diccionary?
len(boston_df)

506

In [81]:
# Let's try the Ridge Regression model

from sklearn.linear_model import Ridge

# Setup random seed

np.random.seed(42)

# Create the data

X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                   test_size=0.2)

# Instantiate Ridge model 

model = Ridge()
model.fit(X_train, y_train)

#Check the score of the Ridge model on test data

model.score(X_test, y_test) #score=r^2


0.6662221670168521

### How do we improve this score?
### what if the Ridge wasn't working?



In [82]:
# Let's try Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor

#Setup random seed
np.random.seed(42)

#Create the data
X = boston_df.drop("target", axis=1)
y = boston_df["target"]


#split de data

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instatiate Random Forest Regressor

rf = RandomForestRegressor(n_estimators=100)
rf.fit(X_train, y_train)

#Evaluate the Random Forest Regresor
rf.score(X_test, y_test)

0.8654448653350507

In [83]:
# Check the Ridge model again

model.score(X_test, y_test)

0.6662221670168521

### 2.2 Choosing and estimator for a clasification problem

Let's go to the map

In [84]:
heart_disease = pd.read_csv("Data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [85]:
len(heart_disease)

303

Consulting the map and it says to try LinearSVC

In [86]:
# Import the LinearSVC estimator class
from sklearn.svm import LinearSVC

#Setup random seed
np.random.seed(42)

#Make the data

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate LinearSVC

clf = LinearSVC(max_iter=1000)
clf.fit(X_train, y_train)

#Evaluate the LinearSVC
clf.score(X_test, y_test)

/Users/vivianameneses/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.8688524590163934

In [87]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [88]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

#Setup random seed
np.random.seed(42)

#Make the data

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

#Evaluate the Random Forest Classifier
clf.score(X_test, y_test)

0.8524590163934426

Tidbit:
1. If you have structured data, used ensemble method
2.  If you have unstructured data, use deep learning or transfer learning

## 3. Fit the model/algorithm on our data use it to make prediction

### 3.1 Fitting the model to the data

Different namer for:
* X= features, features variables, data
* y = labels, targets, targe variables

In [89]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

#Setup random seed
np.random.seed(42)

#Make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# Fit the model to the data(training the machine learning model)
clf.fit(X_train, y_train)

#Evaluate the Random Forest Classifier( use the patterns the model has)
clf.score(X_test, y_test)

0.8524590163934426

In [90]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [91]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

### 3.2 Make predictions using a machine learning model
2 ways to make predictions:
1. predict( )
2. predict_proba ( )

In [92]:
# Use a trained model to make predictions
clf.predict(np.array[1,7,8,3,4]) #this doesn't work...

TypeError: 'builtin_function_or_method' object is not subscriptable

In [93]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [94]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [95]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [96]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [97]:
clf.score(X_test, y_test)

0.8524590163934426

In [98]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

 Make predictions with ' predict_proba() '

In [99]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [100]:
#Podemos ver que el valor de la derecha es mayor, si comparamos con predict(), podemos ver que en la primera fila, seria 0, segunda fila 1,1,0,1...

In [101]:
# Let's predict() on the same data...
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [102]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

'predict()' can also used for refression models-

In [103]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [107]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data

X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into training and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate and fit model

model= RandomForestRegressor(n_estimators=100).fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)


In [108]:
y_preds

array([23.081, 30.574, 16.759, 23.46 , 16.893, 21.644, 19.113, 15.334,
       21.14 , 20.639, 19.787, 19.541,  8.583, 21.85 , 19.531, 25.851,
       19.759,  8.22 , 45.109, 14.712, 24.548, 23.956, 14.548, 22.944,
       15.023, 14.643, 21.137, 14.153, 19.232, 20.666, 19.588, 23.254,
       33.01 , 20.461, 14.271, 15.889, 34.704, 19.154, 20.85 , 24.395,
       18.978, 29.84 , 45.302, 19.447, 22.234, 13.751, 15.511, 24.612,
       18.729, 28.235, 21.21 , 34.218, 17.271, 26.147, 45.279, 21.924,
       15.532, 32.412, 22.212, 20.453, 25.532, 34.326, 28.795, 18.951,
       27.145, 17.181, 13.534, 23.04 , 28.714, 15.802, 20.451, 27.87 ,
       10.193, 21.507, 22.383,  7.265, 20.089, 45.388, 10.88 , 13.053,
       21.322, 12.366, 20.233,  9.135, 20.052, 26.787, 15.277, 23.267,
       23.613, 17.699, 21.617,  7.921, 19.475, 18.807, 22.386, 19.836,
       38.714, 13.159, 12.476, 13.612, 20.205, 23.832])

In [109]:
y_test[:10]

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
76     20.0
316    17.8
140    14.0
471    19.6
500    16.8
Name: target, dtype: float64

In [110]:
np.array(y_test[:10])

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8])

In [111]:
y_preds[:10]

array([23.081, 30.574, 16.759, 23.46 , 16.893, 21.644, 19.113, 15.334,
       21.14 , 20.639])

In [112]:
# Compare the predictions to the truth

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.136382352941176

## 4. Evaluating a machile learning model

3 ways to evaluate Scikit-Learn models/estimators
1. Estimator `score` method
2. The `scoring` parameter
3. Problem-specific metric functions.

### 4.1 Evaluating a model with the `score` method

In [113]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

clf = RandomForestClassifier()

clf.fit(X_train, y_train)



RandomForestClassifier()

In [114]:
clf.scobre(X_train, y_train)

1.0

In [115]:
clf.score(X_test, y_test)

0.8524590163934426

In [121]:
# Score en Random Forest Clasification is accuracy

Let's do the same but for regression...

In [118]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data

X = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into training and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate and fit model

model= RandomForestRegressor(n_estimators=100).fit(X_train, y_train)


In [119]:
model.score(X_test, y_test)

0.8654448653350507

In [120]:
# Score en Random Forest Regression is R^2

### 4.2 Evaluating a model using the `scoring`parameter

In [124]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train);

In [125]:
clf.score(X_test, y_test)

0.8524590163934426

In [126]:
cross_val_score(clf, X, y, cv=5) #cv=cross-validation

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

In [128]:
np.random.seed(42)

# Single training test split score
clf_single_score = clf.score(X_test,y_test)

# Take the mean of 5-fold cross-validation score
clf_cross_val_score = np.mean(cross_val_score(clf, X,y, cv=5))

# Compate the two
clf_single_score, clf_cross_val_score

(0.8524590163934426, 0.8248087431693989)

In [132]:
# Default scoring parameter of classifier = mean accuracy
clf.score(X_test, y_test)

0.8524590163934426

In [133]:
# Scoring parameter set to None by default
cross_val_score(clf, X, y, cv=5, scoring=None)

array([0.78688525, 0.86885246, 0.80327869, 0.78333333, 0.76666667])

### 4.2.1 Classification model evaluation metrics

1. Accuracy
2. Area under ROC curve
3. Confusion matrix
4. Classification report


### Accuracy

In [142]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [137]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

clf = RandomForestClassifier(n_estimators=100)
cross_val_score = cross_val_score(clf, X, y, cv=5)

In [138]:
np.mean(cross_val_score)

0.8248087431693989

In [141]:
print(f"Heart Disease Classifier Cross-Validated Accuracy: {np.mean(cross_val_score)*100:.2f}%")

Heart Disease Classifier Cross-Validated Accuracy: 82.48%
