# Introduction to Scikit-Learn (sklearn)
This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:

0. An end-to-end Scikit-Learno workflow
1. Gettin the data ready
2. Choose the rigth estimator/algotithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluatin a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

## 0. An end-to-end Scikit-Learn workflow

In [ ]:
# Standar imports
import numpy as np
import pandas as pd
import matplotlib.plyplot as plt
%matplotlib inline

In [18]:
import numpy as np

In [12]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [13]:
# Create X (features matrix)
X = heart_disease.drop("target", axis=1) #axis=1 columnas

# Create y (labels)
y = heart_disease["target"]

In [14]:
# 2. Choose the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [15]:
# 3. Fit the model to the training data
# Split the data into training and test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2) #80% entretamiento y 20% para test

In [17]:
# .fit el modelo está entrenando
clf.fit(X_train, y_train);

In [20]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
279   61    1   0       138   166    0        0      125      1      3.6   
17    66    0   3       150   226    0        1      114      0      2.6   
3     56    1   1       120   236    0        1      178      0      0.8   
47    47    1   2       138   257    0        0      156      0      0.0   
80    41    1   2       112   250    0        1      179      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
266   55    0   0       180   327    0        2      117      1      3.4   
9     57    1   2       150   168    0        1      174      0      1.6   
6     56    0   1       140   294    0        0      153      0      1.3   
127   67    0   2       152   277    0        1      172      0      0.0   
76    51    1   2       125   245    1        0      166      0      2.4   

     slope  ca  thal  
279      1   1     2  
17       0   0     2  
3        2   0     2  
47       2   0     2  
80       2   0     2  
..     ...  ..   ...  
266      1   0     2  
9        2   0     2  
6        1   0     2  
127      2   1     2  
76       1   0     2  

[242 rows x 13 columns]

In [19]:
# make a prediction
y_label = clf.predict(np.array([0,2,3,4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [21]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
175   40    1   0       110   167    0        0      114      1      2.0   
189   41    1   0       110   172    0        0      158      0      0.0   
296   63    0   0       124   197    0        1      136      1      0.0   
59    57    0   0       128   303    0        0      159      0      0.0   
255   45    1   0       142   309    0        0      147      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
46    44    1   2       140   235    0        0      180      0      0.0   
83    52    1   3       152   298    1        1      178      0      1.2   
211   61    1   0       120   260    0        1      140      1      3.6   
164   38    1   2       138   175    0        1      173      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   

     slope  ca  thal  
175      1   0     3  
189      2   0     3  
296      1   0     2  
59       2   1     2  
255      1   3     3  
..     ...  ..   ...  
46       2   0     2  
83       1   0     3  
211      1   1     3  
164      2   4     2  
32       2   0     2  

[61 rows x 13 columns]

In [23]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1])

In [24]:
y_test

175    0
189    0
296    0
59     1
255    0
      ..
46     1
83     1
211    0
164    1
32     1
Name: target, Length: 61, dtype: int64

In [25]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train)

1.0

In [26]:
clf.score(X_test, y_test)

0.7213114754098361

In [28]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.82      0.58      0.68        31
           1       0.67      0.87      0.75        30

    accuracy                           0.72        61
   macro avg       0.74      0.72      0.72        61
weighted avg       0.74      0.72      0.72        61



In [29]:
confusion_matrix(y_test, y_preds)

array([[18, 13],
       [ 4, 26]])

In [30]:
accuracy_score(y_test, y_preds) #Accuracy= precisión, exactitud

0.7213114754098361

In [36]:
# 5. Improve a model
# Try different amonut of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...") # Se pone f para concatenar string con variable, en este {i}
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on teste set_{clf.score(X_test, y_test)*100:.2f}%") # :.2 es para dejar en 2 decimales
    print("")

Trying model with 10 estimators...
Model accuracy on teste set_73.77%

Trying model with 20 estimators...
Model accuracy on teste set_68.85%

Trying model with 30 estimators...
Model accuracy on teste set_72.13%

Trying model with 40 estimators...
Model accuracy on teste set_72.13%

Trying model with 50 estimators...
Model accuracy on teste set_75.41%

Trying model with 60 estimators...
Model accuracy on teste set_72.13%

Trying model with 70 estimators...
Model accuracy on teste set_70.49%

Trying model with 80 estimators...
Model accuracy on teste set_72.13%

Trying model with 90 estimators...
Model accuracy on teste set_70.49%



In [38]:
# 6. Save a model and load it
import pickle
pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

In [39]:
loaden_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaden_model.score(X_test, y_test)

0.7049180327868853

In [44]:
loaden_model.predict([[ 40.,   1.,   0., 110., 167.,   0.,   0., 114.,   1.,   2.,   1.,
         0.,   3.]])

array([0])

In [40]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
175   40    1   0       110   167    0        0      114      1      2.0   
189   41    1   0       110   172    0        0      158      0      0.0   
296   63    0   0       124   197    0        1      136      1      0.0   
59    57    0   0       128   303    0        0      159      0      0.0   
255   45    1   0       142   309    0        0      147      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
46    44    1   2       140   235    0        0      180      0      0.0   
83    52    1   3       152   298    1        1      178      0      1.2   
211   61    1   0       120   260    0        1      140      1      3.6   
164   38    1   2       138   175    0        1      173      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   

     slope  ca  thal  
175      1   0     3  
189      2   0     3  
296      1   0     2  
59       2   1     2  
255      1   3     3  
..     ...  ..   ...  
46       2   0     2  
83       1   0     3  
211      1   1     3  
164      2   4     2  
32       2   0     2  

[61 rows x 13 columns]

In [43]:
X_test.iloc[0].values

array([ 40.,   1.,   0., 110., 167.,   0.,   0., 114.,   1.,   2.,   1.,
         0.,   3.])

In [45]:
loaden_model.predict([[ 45.,   1.,   3., 140., 187.,   0.,   1., 154.,   1.,   1.,   2.,
         4.,   2.]])

array([1])

## 1. Getting our data ready to be used with Machine Learning
Thre main thing we have to do:

    1. Split the data into features and labels (usually 'X' & 'y')
    2. Filling(also callen imputing) or disregarding missing values
    3. Converting non-numerical values to numerical values(also called feature encoding)

### 1.1 Make sure it's all numerical

In [47]:
# pd.read_csv("") = cargar csv
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [48]:
# len=largo
len(car_sales) 

1000

In [49]:
# dtype = tipo de dato
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [50]:
# Split into X/y
X = car_sales.drop("Price", axis=1) # Todas las columnas menos la columna precio
y = car_sales["Price"] # nuestra variable y será el precio, lo que queremos estimar

#Split into training and test

X_train, X_test, y_train, y_test = train_test_split(X,
                                                   y,
                                                   test_size=0.2) # 80 % entramiento, 20% test

In [51]:
# Buil ML model

from sklearn.ensemble import RandomForestRegressor # RandomrForestRegressor predice números

model = RandomForestRegressor()
model.fit(X_train, y_train) # se entrena el modelo con esas variables
model.score(X_test, y_test) # se obtiene precisión del modelo


ValueError: could not convert string to float: 'Honda'

In [58]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [59]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [61]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [62]:
dummies = pd.get_dummies(car_sales[["Make","Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [63]:
# Let's refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [64]:
model.score(X_test, y_test)

0.3235867221569877

In [65]:
# probando con dummies
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(dummies,
                                                   y,
                                                   test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [66]:
model.score(X_test, y_test)

0.2920788538619685

### 1.2 What if there wre missing values?
1. Fill them with some value(also known as imputation).
2. Remove the samples with missing data altogether

In [67]:
# Import car sales missing data extended
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [69]:
# ver si hay datos nulos en el csv
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [70]:
# Create X & y
X = car_sales_missing.drop("Price", axis=1)
y= car_sales_missing["Price"]

In [71]:
# Let's try and convert our data in numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [72]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

## Option 1: Fill missing data with Pandas

In [73]:
# Fill the "Make" column
car_sales_missing["Make"].fillna("missing", inplace=True)

# Fill the " Colour" column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the "Odometer(KM)" column
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "doors" column
car_sales_missing["Doors"].fillna(4, inplace=True)


In [74]:
# Check our dataframe again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [75]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace=True)

In [76]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [77]:
len(car_sales_missing)

950

In [78]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [80]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # se toman las 2 col categóricas, más las puertas, debido a que no se modifican
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                   remainder = "passthrough")
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### Option 2: Fill missing values with Scikit-learn